### PR TITLE
ViewportPastingDecorator: use pageYOffset instead of scrollY

### LINKED ISSUE #110: the scrolling web page screenshots taken in IE11 with selenium 3.5 and ashot is not working. it is creating partial image.
the scrolling web page screenshots taken in IE11 with selenium 3.5 and ashot is not working. it is creating partial image.

IE Version: 11
Selenium Version: Version 3.5.3
OS: 2012 R2 server
Java: 1.8

The below is the code used.

final Screenshot screenshot = new AShot()
                    .shootingStrategy(ShootingStrategies.viewportPasting(1000))
                    .takeScreenshot(driver);

            final BufferedImage image = screenshot.getImage();

            try {
                
                ImageIO.write(image, "png", new File("scrsht\\" + filename + "- ie -" + dateFormat.format(new Date()) + ".png"));

            } catch (IOException ex) {
                
                

            }

### PR DESCRIPTION
**Pull request by naruoga**
to improve browsers compatibility; especially in IE9-, we now can use VIewportPasting() strategy, hopefully it might fix #110

### CODE REVIEW

**Comment by naruoga** [comment]
I'm not a Web professional I've just referred the answer to the following question:

https://stackoverflow.com/questions/44757869/window-pageyoffset-vs-window-scrolly-on-ie11

> Window.scrollY is not supported in IE(11 or below). Window.pageYOffset works on "all" browsers including IE9-11. Window.scrollY works on "all" browsers except IE.

I confirmed my change with 'mvn test` on my Ubuntu box, and use a small example:https://github.com/naruoga/AShotTest

In the issue page in my repo, I filed 4 issues summarize results:

- 2 Linux env (FF, Chrome) were OK (no regression in limited env / use-case)
- 1 Win env (IE) had successfully done (#110 is solved)
- 1 Win env (Edge) had done with fail not in AShot calling, might be an environment problem 
    - it's a several-months ago buidt VM

Another tests are welcome!

**Comment by naruoga** [comment]
Hmm, travis said something wrong... I'll take a look later

**Comment by naruoga** [comment]
Hello, the three issues, which are currently open ATM, got failure results with the same result, so I thought that is from Travis's problem, not from Japanese env...  Could anyone take a look?

**Comment by naruoga** [comment]
@pazone I hope you still have interest this cute library... I found that the Travis fail is just because our .travis.yml still have the Oracle7 JDK entry, and I sent another PR about this #142 .  Please take a look!

File: src/main/java/ru/yandex/qatools/ashot/shooting/ViewportPastingDecorator.java [hunk 1]
```diff
@@ -43,6 +43,18 @@ public BufferedImage getScreenshot(WebDriver wd, Set<Coords> coordsSet) {
...
+        }
+        System.out.printf("pageWidth = %d,pageHeight = %d,viewportHeight = %d, shootingArea.height = %d\n",
+                pageWidth, pageHeight, viewportHeight, shootingArea.height);
+        if (coordsSet == null)  {
+            System.out.println("coordsSet is null");
+        } else {
+            Coords c = Coords.unity(coordsSet);
+            System.out.printf("Coords.unity(coordsSet) = (%d,%d,%d,%d)\n", c.x, c.y, c.width, c.height);
+        }
+
```
Comment (naruoga) [inline src/main/java/ru/yandex/qatools/ashot/shooting/ViewportPastingDecorator.java]: The code above should be removed... because it had wrongly committed from my debugging code

File: src/main/java/ru/yandex/qatools/ashot/shooting/ViewportPastingDecorator.java [hunk 2]
```diff
@@ -86,8 +98,11 @@ protected void scrollVertically(JavascriptExecutor js, int scrollY) {
 
     private Coords getShootingCoords(Set<Coords> coords, int pageWidth, int pageHeight, int viewPortHeight) {
         if (coords == null || coords.isEmpty()) {
+            System.out.printf("getShootingCoords: new Coords(%d, %d, %d, %d)\n", 0, 0, pageWidth, pageHeight);
             return new Coords(0, 0, pageWidth, pageHeight);
         }
+        Coords c = Coords.unity(coords);
+        System.out.printf("getShootingCoords: extendShootingArea(Cords.unity(coords) = (%d, %d, %d, %d)\n", c.x, c.y, c.width, c.height);
         return extendShootingArea(Coords.unity(coords), viewPortHeight, pageHeight);
```
Comment (ogasawara-shift) [inline src/main/java/ru/yandex/qatools/ashot/shooting/ViewportPastingDecorator.java]: These code also should be removed... X(

File: src/main/java/ru/yandex/qatools/ashot/shooting/ViewportPastingDecorator.java (hunk 1 above)
Comment (naruoga) [reply src/main/java/ru/yandex/qatools/ashot/shooting/ViewportPastingDecorator.java]: wrong commit removed

File: src/main/java/ru/yandex/qatools/ashot/shooting/ViewportPastingDecorator.java (hunk 2 above)
Comment (naruoga) [reply src/main/java/ru/yandex/qatools/ashot/shooting/ViewportPastingDecorator.java]: wrong commit removed

**Comment by pazone** [comment]
Thanks!

**Comment by tmshft** [comment]
Hi. @pazone 
Would you tell me when you are going to release this awesome commit?

**Comment by pazone** [comment]
Hi @shift-morikawa . It is already available in a snapshot version: `1.6.0-SNAPSHOT`. Please keep in mind that package names and group id were changed. I'm going to make an `1.6.0` release soon but I have to update docs before.

**Comment by kriegaex** [comment]
Sorry to ask in a merged PR first before opening a new issue, but I just switched from 1.5.4 to 1.6.0-SNAPSHOT (not nice because I cannot release with snapshot dependencies in my POM).
  * It solves an IE issue similar to #70 and #110 and my sample test also works in Chrome (also headless), Opera, Firefox, Edge (Chromium), just like before. So far, so good.
  * But in 1.5.4 the same test used to run in PhantomJS, now with this version it fails. I saw you closed a different PJS issue #92 before because PJS is no longer maintained. But the same is true for IE and it is still supported. Is there any chance you would accept and investigate on a PJS issue if I opened one?

**Comment by valfirst** [comment]
@kriegaex the key difference between IE and PhantomJS is that PhantomJS is not used by users, but IE could be a kind of legacy requirement and it's still used somewhere. If you really need to support PhantomJS (why not switch to headless Chrome?) you can open a new issue or put a comment to reopen existing one and then provide PR.

**Comment by kriegaex** [comment]
Actually I wanted to avoid a meta discussion and having to justify PJS usage, but to answer your questions:
  * I do use headless Chrome, as mentioned in my question. I have a sample project configurable for multiple browsers, so I can quickly test compatibility.
  * I mainly work as an (agile) coach. In that capacity I also introduce developers to test automation concepts and some teams decide or have decided before my arrival already to also use PJS because it does not need to be installed locally like Chrome or the other browsers, which is especially helpful on CI servers without any attached monitors. You just download and run PJS.
  * PJS may be out of active development due to lack of resources, but I have yet to find another browser designed to be run strictly headlessly with a solid feature set comparable to a modern desktop browser and usable from Java (not JS).
 * As for providing a PR, that is beyond my technical means. My Java is pretty solid, even though I am not a professional developer, but I speak no JS. I see JS errors on the PJS console before finally Selenium indirectly AShot throw exceptions. I am a user of this product, not a code contributor. My humble contribution to this project can be feedback and (re-)testing in order to help you make it better.

Back to my first question: Does my hint that AShot 1.5.4 works with PJS, but the current snapshot does not, ring any bells? What has changed since then? Maybe you already have an idea. Otherwise, would it help to know the exact commit which broke PJS? Maybe I can `git bisect` it then.
